### ISSUE TITLE
[1.16.5] Advancement Load Fix Server Spam

### ISSUE THREAD

**Issue by Cixon** [SistrScarlet/LittleMaidReBirth#1]
**Issue :** My Forge 36.0.42 server was spammed with messages because of LittleMaidReBirth.
This causes the server to lag and freeze. Critical bug!  (´；ω；`)

**How to :**
1.) Created a server with Forge 36.0.42
2.) Use LMML 2.3.10  and LMRB 2.4.1
3.) Tame a little maid. Set maid to wait mode .
4.) Explore the world in creative mode .
5.) See Server logs .

**Screenshot :**
![Screenshot (109)](https://user-images.githubusercontent.com/69068153/109741218-3b951600-7b92-11eb-96fb-7d19420c4701.png)

Version
________________
LMML 2.3.10
LMRB  2.4.1

**Comment by Cixon** [comment]
日本語が話せなくてごめんなさい、アメリカ人です。

**Comment by SistrScarlet** [comment]
6f127e7 にて修正しました。

**Comment by Cixon** [comment]
ありがとうございました ！
