### ISSUE TITLE
[1.16.5] Advancement Loading Server Spam is Back! :(

### ISSUE THREAD

**Issue by Cixon** [SistrScarlet/LittleMaidReBirth#2]
**Bug:** 
![advancementfixbug](https://user-images.githubusercontent.com/69068153/110873528-94059b00-8297-11eb-8c83-f26e5e43a955.gif)
![Screenshot (121)](https://user-images.githubusercontent.com/69068153/110874020-974d5680-8298-11eb-9c88-242805a7387b.png)

**Forge Server And Client:**
1.16.5 - 36.0.42

**Mod Versions:**
LMRB - v2.5.1 
LMML- v2.3.10

**Comment by SistrScarlet** [comment]
e2856cc9c50865c692950845ca798bba0bcb5d66 にて修正しました。
ご報告ありがとうございました。
