### ISSUE TITLE
リトルメイドスキンパックの読み込みの問題

### ISSUE THREAD

**Issue by erer00gg** [SistrScarlet/LittleMaidReBirth#3]
「littleMaidMob-im @ stex-Chloe2-162」のCHIHAYAcolorスキンは正しく表示できません。
![2021-04-05_07 47 14](https://user-images.githubusercontent.com/58005561/113522414-4a307c00-95db-11eb-86c1-7ba8efb413d0.png)

使用したスキンパック：littleMaidMob-Elsa_Chloe_Beverly-1.0.jar
littleMaidMob-im @ stex-Chloe2-162.zip

**Comment by SistrScarlet** [comment]
おそらくテクスチャパック側の問題です。
そのテクスチャパックが配布されているサイトへのURLをください。
また、検証のため導入しているModとそのバージョンをすべて記載してください。

**Comment by erer00gg** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1287042-1-7-10-1-8-littlemaidmob-final-versions-updated?comment=3

**Comment by SistrScarlet** [comment]
テクスチャパック内のomakeフォルダに入っているテクスチャは、使用モデルの指定がChloe2ではないため、デフォルトのモデルが読み込まれています。
テクスチャが入っているフォルダの名前の後ろに_Chloe2を付けることで解決すると思われます。

本来であれば正常に読み込めないテクスチャは表示するべきではないのですが、以下の理由により仕様です。
・ファイルの読み込み後に、テクスチャの指定モデルの実在チェックが必要になる
・認識されていないのか、読み込めたが正常ではないのか、の区別が付きやすい

**Comment by SistrScarlet** [comment]
テクスチャパック内のomakeフォルダに入っているテクスチャは、使用モデルの指定がChloe2ではないため、デフォルトのモデルが読み込まれています。
テクスチャが入っているフォルダの名前の後ろに_Chloe2を付けることで解決すると思われます。

本来であれば正常に読み込めないテクスチャは表示するべきではないのですが、以下の理由により仕様です。
・ファイルの読み込み後に、テクスチャの指定モデルの実在チェックが必要になる
・認識されていないのか、読み込めたが正常ではないのか、の区別が付きやすい
