### ISSUE TITLE
メイドの視点には問題があります

### ISSUE THREAD

**Issue by erer00gg** [SistrScarlet/LittleMaidReBirth#4]
Beverly、Chloeモデルを使用したリトルメイドの視野角が高すぎます。 モデル選択ページに再度入ると、リトルメイドの視点が高すぎるという問題は解決できますが、ワールドをリロードすると元の状態に戻ります。このバグは修正できますか？

![2021-04-09_06 43 21](https://user-images.githubusercontent.com/58005561/114094636-83c4f800-98f7-11eb-8d76-20ed76efa907.png)
![2021-04-09_06 43 33](https://user-images.githubusercontent.com/58005561/114094644-86275200-98f7-11eb-969e-87424424c989.png)

**Comment by SistrScarlet** [comment]
そのMobはLittleMaidEntityではなくMultiModelEntityですよね。
LittleMaidModelLoaderの方で修正しておきます。
