### ISSUE TITLE
ヘルスキャップの調整

### ISSUE THREAD

**Issue by Hakoyu** [SistrScarlet/LittleMaidReBirth#9]
ヘルスキャップの調整は可能か
たった20点というのは、やはり低すぎる

**Comment by SistrScarlet** [comment]
きちんとした防具を着せて、お砂糖を十分に持たせた上で、倒されるような事態があまり想定できません。
また、体力上限の変更は、バニラの属性の仕様上少し面倒です。
お砂糖による体力回復量を増やすコンフィグは既に存在しているので、そちらをお使いください。
